### ISSUE TITLE
Stability of fmod-gdnative for smaller / quick-turnaround projects?

### ISSUE THREAD

**Issue by rcoppy** [utopia-rise/fmod-gdnative#144]
Hello! 

Once a year around the end of January I get together with some sound designer friends and we build an entry for Global Game Jam; [this past year we used FMOD with Unity](https://rcoppy.itch.io/claymore-ham-road-2-reboot). 

This year I'd really like to try using FMOD with Godot, via your plugin. Having read through a lot of the issue posts and open PRs, it seems like you guys are really active and the code is relatively stable 🙂 

I have two questions: 
- Do you guys think the experience of using this plugin is seamless enough that it's practical to try and use for a 48 hour gamejam? (There's not a ton of time for troubleshooting just because of the compressed development window)

- If my team did end up using this plugin for our gamejam project, are there any particular features you'd want us to stress test for you? (e.g. if the Godot4 port is stable enough to be alpha-ready, we could try to use it and find bugs)

One other thing--a couple months back [I asked over on the FMOD forum about official godot support](https://qa.fmod.com/t/possibility-of-official-support-for-the-godot-engine/19333), and it's something the devs over there are really interested in but don't have the staffing resources for. Have you guys ever thought about seeing if you could get FMOD to sponsor you?

Cheers 🙂

**Comment by CedNaru** [comment]
Hello, 
Thanks for the compliment about being active, even if we are not as much as we would want to on it, having several higher priority projects in the work. There are many features we have wanted for a long time, but didn't take enough time for then and in the process kinda pushed them back from when Godot 4.0 is ready.

> Do you guys think the experience of using this plugin is seamless enough that it's practical to try and use for a 48 hour gamejam? (There's not a ton of time for troubleshooting just because of the compressed development window)

It's not optimal for gamejams yet, in my opinion. The next milestone after adapting to Godot 4.0 is to add many Fmod nodes to Godot. That way, you will be able to use FMOD features without relying that much on scripts. But before that, it might be too risky to only rely on the API exposed by the plugin because errors or misunderstanding are quick to happen.

> If my team did end up using this plugin for our gamejam project, are there any particular features you'd want us to stress test for you? (e.g. if the Godot4 port is stable enough to be alpha-ready, we could try to use it and find bugs). 
More testing is always welcome, of course. But I can't really think of anything to stress test. I guess we never really tried to play many events and sounds at the same time, but they are processes by FMOD anyway, there is no obvious reason why our plugin itself would be the bottleneck. 
The better feedback to get would about the parts of the plugin that could be streamlined or made less ambigous.

> Have you guys ever thought about seeing if you could get FMOD to sponsor you?
We contacted them once, not for sponsorship but to be able to distribute the FMOD libs directly in our releases, so people don't have to download them manually, but it was inconclusive. Sponsorship would be nice indeed, but we never really thought about that.

**Comment by bitbrain** [comment]
> It's not optimal for gamejams yet, in my opinion. The next milestone after adapting to Godot 4.0 is to add many Fmod nodes to Godot. That way, you will be able to use FMOD features without relying that much on scripts. But before that, it might be too risky to only rely on the API exposed by the plugin because errors or misunderstandings are quick to happen.

Appending to @CedNaru's point: once we have the nodes in place, FMOD can be a great accelerator during gamejams. The audio person can directly try out sounds on the fly inside the game rather than guessing around how things will sound ingame.

> Have you guys ever thought about seeing if you could get FMOD to sponsor you?

There is this ticket to solve exactly that problem: https://github.com/utopia-rise/fmod-gdnative/issues/110. @benbatt is a developer from FMOD and reached out to us but by the looks of it, Godot is still too niche to be considered for sponsoring. Our hope is that once Godot 4 releases and more studios picking it up, that FMOD will come back to us and re-considers our suggestion.

**Comment by rcoppy** [comment]
Amazing!! Thanks for the pointers :)
