### ISSUE TITLE
Memory leakage when not initializing Fmod

### ISSUE THREAD

**Issue by 2shady4u** [utopia-rise/fmod-gdnative#58]
I'm getting some memory leakage in my project, but only when I don't call `Fmod.init()`

![image](https://user-images.githubusercontent.com/42484461/105033123-fbe9f300-5a57-11eb-99ad-df3763c24778.png)

This happens because the Fmod GDNative instance is created on _ready(), but not freed automatically when Fmod.gd exists the tree.

**A possible solution:**
Free the `fmod_godot` variable (containing the GDNative instance) in an `_exit_tree()`-function as such:
![image](https://user-images.githubusercontent.com/42484461/105032924-bcbba200-5a57-11eb-8c05-a287d60182c9.png)

This seems to get rid of the memory leakage.

NOTE: I haven't thoroughly tested this! There might be issues when you are actually using Fmod! (This could be solved by adding an if-loop that checks if the `fmod_godot` variable is null or not)

**How to replicate:**
Just add the FMOD addons folder and set `verbose_output` to true in the ProjectSettings. Running the game and then quitting it (by pressing the X button) will nag about memory leakage.

**Comment by 2shady4u** [comment]
Or maybe the .shutdown() should be called automatically on _exit_tree instead of just freeing it? That's also a possibility!

**Comment by 2shady4u** [comment]
Small update/further issues (?):

When I build my Godot Project on Gitlab CI I get following memory leakage issues:
![image](https://user-images.githubusercontent.com/42484461/105065826-93623c80-5a7e-11eb-8662-abd33320ab11.png)

They could be related? Or this could be an entire new issue?

**Comment by piiertho** [comment]
I think the last post is related.  
Engine cannot clean ScriptLanguage GDNative implementation related fields (Like `StringName` to easily retrieve methods and classes) because script is still in use.  
It is clearly a bug from the gdscript wrapper.  
@CedNaru what do you think about the idea of calling `shutdown` when exiting tree ?

**Comment by CedNaru** [comment]
It makes sense. 
the GDscript wrapper is supposed to be an autoload so I have never checked about the effects when you close the Engine.
If it continues despite that fix, we may need to add lines to the `fmod_gdnative_terminate` function in the C++ code.

**Comment by CedNaru** [comment]
I think I will bound the life of `godot_fmod` to the life of the wrapper node.
This means not using ready, enter_tree, or exist_tree. I'm going to create the instance in _init() and kill it in a destructor function, so the Gdnative script instance is not freed when we exit the tree but when it's actually destroyed.
In pratice, it doesn't make a difference to use exit_tree or a destructor because it's an Autoload. But I prefer to not introduce some weird behavior if someone wants for whatever reason to remove/add the autoload  from/to the SceneTree at runtime.
